version: '3.8'

services:
  mongodb:
    image: mongo:5.0.26
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
